[package]
name = "bench_object_store"
description = "benchmark for table scans on object stores"
publish = false
version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
include.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
categories.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
dotenv = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
object_store = { workspace = true, features = ["aws"] }
simplelog = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
vortex = { workspace = true, features = ["object_store"] }

[lints]
workspace = true
